blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://relizy.dev
    about: Check the official documentation before opening an issue
  - name: 💬 Discussions
    url: https://github.com/LouisMazel/relizy/discussions
    about: Ask questions and discuss with the community
  - name: 📝 Code of Conduct
    url: https://github.com/LouisMazel/relizy/blob/main/.github/CODE_OF_CONDUCT.md
    about: Read the code of conduct before opening an issue
  - name: 📝 Contributing Guidelines
    url: https://github.com/LouisMazel/relizy/blob/main/CONTRIBUTING.md
    about: Read the contributing guidelines before opening an issue
